language: java
dist: xenial
jdk:
  - openjdk13
os: linux
deploy:
  provider: heroku
  strategy: "api"
  edge: true
  api_key: "82a74cf8-171a-4054-9364-8f02f19bbe4e"
  app: tlas-shop
  on:
    branch: master
after_success:
              - bash <(curl -s https://codecov.io/bash)