language: java
dist: xenial
jdk:
  - openjdk13
os: linux
deploy:
  provider: heroku
  strategy: "api"
  edge: true
  api_key: "8b27acc7-27a2-44ab-85c5-3ddd0c43a2bf"
  app: tlas-shop
  on:
    branch: master
after_success:
              - bash <(curl -s https://codecov.io/bash)